/*
  ALL GAME CONTENT LIVES HERE.
  Add, remove or edit entries freely — the app picks them up automatically.
  Keep the same shape as the existing entries (and mind the commas!).
*/
window.BACKSEAT_DATA = {

  /* ---------- Riddles: q = question, a = answer ---------- */
  riddles: [
    { q: "I have cities but no houses, forests but no trees, and water but no fish. What am I?", a: "A map" },
    { q: "What has keys but can't open locks?", a: "A piano" },
    { q: "What gets wetter the more it dries?", a: "A towel" },
    { q: "What has a neck but no head?", a: "A bottle" },
    { q: "What can travel around the world while staying in a corner?", a: "A stamp" },
    { q: "The more you take, the more you leave behind. What are they?", a: "Footsteps" },
    { q: "What has hands but can't clap?", a: "A clock" },
    { q: "What has one eye but can't see?", a: "A needle" },
    { q: "What goes up but never comes down?", a: "Your age" },
    { q: "I'm tall when I'm young and short when I'm old. What am I?", a: "A candle" },
    { q: "What has many teeth but can't bite?", a: "A comb" },
    { q: "What can you catch but not throw?", a: "A cold" },
    { q: "What has a head and a tail but no body?", a: "A coin" },
    { q: "What is full of holes but still holds water?", a: "A sponge" },
    { q: "What has to be broken before you can use it?", a: "An egg" },
    { q: "What runs but never walks, has a mouth but never talks?", a: "A river" },
    { q: "What word is spelled wrong in every dictionary?", a: "\"Wrong\"" },
    { q: "What can fill a room but takes up no space?", a: "Light" },
    { q: "What has four wheels and flies?", a: "A garbage truck" },
    { q: "What belongs to you, but other people use it more than you do?", a: "Your name" },
    { q: "If you pass the person in second place in a race, what place are you in?", a: "Second place" },
    { q: "What has lots of eyes but can't see?", a: "A potato" },
    { q: "What building has the most stories?", a: "A library" },
    { q: "Forward I'm heavy, backward I'm not. What am I?", a: "A ton" },
    { q: "What comes once in a minute, twice in a moment, but never in a thousand years?", a: "The letter M" },
    { q: "What has a thumb and four fingers but isn't alive?", a: "A glove" },
    { q: "What starts with T, ends with T, and has T in it?", a: "A teapot" },
    { q: "What has a bottom at the top?", a: "Your legs" },
  ],

  /* ---------- Trivia: a = correct answer, wrong = three wrong answers ---------- */
  trivia: [
    {
      id: "geo", name: "Geography", blurb: "Maps, capitals & wild places", color: "#7cf0ff",
      questions: [
        { q: "What is the largest ocean on Earth?", a: "Pacific", wrong: ["Atlantic", "Indian", "Arctic"] },
        { q: "What is the capital of Australia?", a: "Canberra", wrong: ["Sydney", "Melbourne", "Perth"] },
        { q: "What is the longest river in South America?", a: "Amazon", wrong: ["Paraná", "Orinoco", "Magdalena"] },
        { q: "Which US state has the most coastline?", a: "Alaska", wrong: ["California", "Florida", "Hawaii"] },
        { q: "Mount Kilimanjaro is in which country?", a: "Tanzania", wrong: ["Kenya", "Uganda", "Ethiopia"] },
        { q: "What is the smallest country in the world?", a: "Vatican City", wrong: ["Monaco", "San Marino", "Liechtenstein"] },
        { q: "What is the largest hot desert in the world?", a: "Sahara", wrong: ["Gobi", "Kalahari", "Arabian"] },
        { q: "Historic Route 66 begins in which city?", a: "Chicago", wrong: ["St. Louis", "Detroit", "Kansas City"] },
        { q: "How many US states border Canada?", a: "13", wrong: ["11", "12", "14"] },
        { q: "Which country has the most natural lakes?", a: "Canada", wrong: ["Russia", "United States", "Finland"] },
      ],
    },
    {
      id: "sci", name: "Science & Nature", blurb: "Planets, animals & the human body", color: "#b8ff6b",
      questions: [
        { q: "Which planet is known as the Red Planet?", a: "Mars", wrong: ["Venus", "Jupiter", "Mercury"] },
        { q: "What is the chemical symbol for gold?", a: "Au", wrong: ["Ag", "Gd", "Go"] },
        { q: "How many bones are in the adult human body?", a: "206", wrong: ["186", "212", "226"] },
        { q: "What is the fastest land animal?", a: "Cheetah", wrong: ["Pronghorn", "Lion", "Greyhound"] },
        { q: "Which gas do plants absorb from the air?", a: "Carbon dioxide", wrong: ["Oxygen", "Nitrogen", "Helium"] },
        { q: "What is the hardest natural substance?", a: "Diamond", wrong: ["Quartz", "Granite", "Topaz"] },
        { q: "How many hearts does an octopus have?", a: "3", wrong: ["1", "2", "8"] },
        { q: "What is the closest star to Earth?", a: "The Sun", wrong: ["Proxima Centauri", "Sirius", "Polaris"] },
        { q: "At sea level, water boils at what temperature in °F?", a: "212°F", wrong: ["100°F", "180°F", "200°F"] },
        { q: "What is the largest organ of the human body?", a: "Skin", wrong: ["Liver", "Brain", "Lungs"] },
      ],
    },
    {
      id: "film", name: "Movies & TV", blurb: "Quotes, characters & classics", color: "#ff5fa2",
      questions: [
        { q: "Which film features the line \"I'll be back\"?", a: "The Terminator", wrong: ["Die Hard", "RoboCop", "Predator"] },
        { q: "What is the name of the cowboy toy in Toy Story?", a: "Woody", wrong: ["Buzz", "Jessie", "Bullseye"] },
        { q: "In Finding Nemo, what kind of fish is Dory?", a: "Blue tang", wrong: ["Clownfish", "Angelfish", "Pufferfish"] },
        { q: "Which road trip comedy follows the Griswold family?", a: "National Lampoon's Vacation", wrong: ["Little Miss Sunshine", "RV", "Planes, Trains and Automobiles"] },
        { q: "Which show is set in the fictional town of Hawkins, Indiana?", a: "Stranger Things", wrong: ["Twin Peaks", "Riverdale", "Gravity Falls"] },
        { q: "Who directed Jurassic Park?", a: "Steven Spielberg", wrong: ["James Cameron", "George Lucas", "Ridley Scott"] },
        { q: "In the 1939 film, what color are Dorothy's slippers?", a: "Ruby red", wrong: ["Silver", "Gold", "Emerald green"] },
        { q: "What is the name of the coffee shop in Friends?", a: "Central Perk", wrong: ["The Daily Grind", "Java Joe's", "Monk's Café"] },
        { q: "What is Lightning McQueen's race number in Cars?", a: "95", wrong: ["43", "86", "12"] },
        { q: "Which film won the first-ever Oscar for Best Animated Feature?", a: "Shrek", wrong: ["Toy Story", "Monsters, Inc.", "Spirited Away"] },
      ],
    },
    {
      id: "music", name: "Music", blurb: "Road songs, legends & instruments", color: "#ffd84d",
      questions: [
        { q: "Which band recorded \"Bohemian Rhapsody\"?", a: "Queen", wrong: ["The Who", "Led Zeppelin", "The Rolling Stones"] },
        { q: "How many strings does a standard guitar have?", a: "6", wrong: ["4", "5", "7"] },
        { q: "Who originally recorded \"Life Is a Highway\"?", a: "Tom Cochrane", wrong: ["Rascal Flatts", "Bon Jovi", "Bryan Adams"] },
        { q: "Which artist is known as the \"King of Pop\"?", a: "Michael Jackson", wrong: ["Elvis Presley", "Prince", "Justin Timberlake"] },
        { q: "Who wrote and sang \"On the Road Again\"?", a: "Willie Nelson", wrong: ["Johnny Cash", "Dolly Parton", "Kenny Rogers"] },
        { q: "Which Beatles album cover shows the band crossing the street?", a: "Abbey Road", wrong: ["Revolver", "Let It Be", "Help!"] },
        { q: "How many keys are on a standard piano?", a: "88", wrong: ["76", "92", "100"] },
        { q: "Taylor Swift's album \"1989\" is named after what?", a: "The year she was born", wrong: ["Her first concert", "Her childhood address", "A favorite movie"] },
        { q: "Which instrument was Louis Armstrong famous for?", a: "Trumpet", wrong: ["Saxophone", "Trombone", "Clarinet"] },
        { q: "Which country is ABBA from?", a: "Sweden", wrong: ["Norway", "Denmark", "Finland"] },
      ],
    },
    {
      id: "history", name: "History", blurb: "Empires, inventors & firsts", color: "#ffb86b",
      questions: [
        { q: "Who was the first person to walk on the Moon?", a: "Neil Armstrong", wrong: ["Buzz Aldrin", "Yuri Gagarin", "John Glenn"] },
        { q: "In what year did the Titanic sink?", a: "1912", wrong: ["1905", "1915", "1923"] },
        { q: "Which of the Seven Wonders of the Ancient World still stands?", a: "Great Pyramid of Giza", wrong: ["Colossus of Rhodes", "Hanging Gardens of Babylon", "Lighthouse of Alexandria"] },
        { q: "Who was the first President of the United States?", a: "George Washington", wrong: ["John Adams", "Thomas Jefferson", "Benjamin Franklin"] },
        { q: "Which civilization built Machu Picchu?", a: "Inca", wrong: ["Aztec", "Maya", "Olmec"] },
        { q: "In what year did the Berlin Wall fall?", a: "1989", wrong: ["1985", "1991", "1979"] },
        { q: "Who received the first US patent for the telephone?", a: "Alexander Graham Bell", wrong: ["Thomas Edison", "Nikola Tesla", "Samuel Morse"] },
        { q: "Which company built the Model T?", a: "Ford", wrong: ["Chevrolet", "Dodge", "Cadillac"] },
        { q: "What was the first US national park?", a: "Yellowstone", wrong: ["Yosemite", "Grand Canyon", "Zion"] },
        { q: "Which country gave the Statue of Liberty to the United States?", a: "France", wrong: ["England", "Spain", "Italy"] },
      ],
    },
    {
      id: "food", name: "Food & Drink", blurb: "Snack-stop knowledge", color: "#c69bff",
      questions: [
        { q: "What is the main ingredient in guacamole?", a: "Avocado", wrong: ["Lime", "Tomato", "Green pepper"] },
        { q: "Paella comes from which country?", a: "Spain", wrong: ["Mexico", "Portugal", "Italy"] },
        { q: "Which nut is used to make marzipan?", a: "Almond", wrong: ["Cashew", "Hazelnut", "Pistachio"] },
        { q: "Which fruit wears its seeds on the outside?", a: "Strawberry", wrong: ["Raspberry", "Kiwi", "Blueberry"] },
        { q: "Parmesan cheese comes from which country?", a: "Italy", wrong: ["France", "Switzerland", "Greece"] },
        { q: "What is the main ingredient in hummus?", a: "Chickpeas", wrong: ["Lentils", "White beans", "Peas"] },
        { q: "What is the most expensive spice by weight?", a: "Saffron", wrong: ["Vanilla", "Cardamom", "Cinnamon"] },
        { q: "Which pasta is shaped like little ears?", a: "Orecchiette", wrong: ["Farfalle", "Fusilli", "Penne"] },
        { q: "Tofu is made from which bean?", a: "Soybean", wrong: ["Black bean", "Kidney bean", "Mung bean"] },
        { q: "Oranges are famous for which vitamin?", a: "Vitamin C", wrong: ["Vitamin A", "Vitamin D", "Vitamin K"] },
      ],
    },
  ],

  /* ---------- Emoji rebus: e = emoji clue, a = answer, type = hint shown to players ---------- */
  rebus: [
    { e: "🌧️ 🎀", a: "Rainbow", type: "Word" },
    { e: "🔥 🪰", a: "Firefly", type: "Word" },
    { e: "⭐ 🐟", a: "Starfish", type: "Word" },
    { e: "🧈 🪰", a: "Butterfly", type: "Word" },
    { e: "☀️ 🌻", a: "Sunflower", type: "Word" },
    { e: "🌲 🍎", a: "Pineapple", type: "Word" },
    { e: "🦶 ⚽", a: "Football", type: "Word" },
    { e: "🌙 💡", a: "Moonlight", type: "Word" },
    { e: "🐴 👞", a: "Horseshoe", type: "Word" },
    { e: "🔥 🐶", a: "Hot dog", type: "Word" },
    { e: "🎤 👋", a: "Microwave", type: "Word" },
    { e: "💧 🍈", a: "Watermelon", type: "Word" },
    { e: "🚪 🔔", a: "Doorbell", type: "Word" },
    { e: "🐱 🐟", a: "Catfish", type: "Word" },
    { e: "🌍 🐛", a: "Earthworm", type: "Word" },
    { e: "❄️ ⛄ 👸", a: "Frozen", type: "Movie" },
    { e: "🦁 👑", a: "The Lion King", type: "Movie" },
    { e: "🕷️ 🧑", a: "Spider-Man", type: "Movie" },
    { e: "🦈 🦷", a: "Jaws", type: "Movie" },
    { e: "👻 💥", a: "Ghostbusters", type: "Movie" },
    { e: "🔍 🐠", a: "Finding Nemo", type: "Movie" },
    { e: "⭐ ⚔️", a: "Star Wars", type: "Movie" },
    { e: "🏠 🎈 🎈 🎈", a: "Up", type: "Movie" },
    { e: "🐀 👨‍🍳", a: "Ratatouille", type: "Movie" },
    { e: "🦖 🏝️", a: "Jurassic Park", type: "Movie" },
  ],

  /* ---------- Road bingo: things to spot out the window ---------- */
  bingo: [
    "Red car", "Yellow car", "Cow", "Horse", "Out-of-state plate", "Motorcycle", "Bridge", "Water tower",
    "Semi truck", "RV", "Police car", "Traffic cone", "Lawyer billboard", "Dog in a car", "Train", "Tunnel",
    "Red barn", "Wind turbine", "Funny bumper sticker", "Convertible", "Speed limit 70", "Deer crossing sign",
    "School bus", "Tractor", "Flag", "Car towing a boat", "Bike rack", "Motel sign", "Exit 100+", "Rest area",
    "Mile marker ending in 0", "Animal-shaped cloud", "Someone singing", "Pickup truck", "Airplane",
    "Bird on a wire", "Toll booth", "New state sign", "River", "Mountain", "Ice cream sign", "Gas under $3",
    "Hay bales", "Ambulance", "Horse trailer", "Church steeple", "Roadside fruit stand", "Hawk", "Cell tower",
  ],

  /* ---------- Would you rather: [option A, option B] ---------- */
  wouldYouRather: [
    ["Only be able to whisper", "Only be able to shout"],
    ["Have a rewind button for your life", "Have a pause button for your life"],
    ["Explore outer space", "Explore the deep ocean"],
    ["Always be 10 minutes late", "Always be 20 minutes early"],
    ["Have a personal chef", "Have a personal driver"],
    ["Be able to fly", "Be able to teleport"],
    ["Live without music", "Live without movies"],
    ["Fight one horse-sized duck", "Fight a hundred duck-sized horses"],
    ["Speak every language", "Play every instrument"],
    ["Road trip with no snacks", "Road trip with no music"],
    ["Control the music on every road trip", "Pick every restaurant on every road trip"],
    ["Live in a treehouse", "Live on a houseboat"],
    ["Be the funniest person in the room", "Be the smartest person in the room"],
    ["Own a dragon", "Be a dragon"],
    ["Only eat sweet food", "Only eat savory food"],
    ["Never need to sleep", "Never need to eat"],
    ["Visit the past", "Visit the future"],
    ["Talk to animals", "Read minds"],
    ["Sing instead of talk", "Dance everywhere you walk"],
    ["Get unlimited free flights", "Get unlimited free hotel stays"],
    ["Sit in traffic for 3 hours", "Take a 3-hour scenic detour"],
    ["Have a pet elephant the size of a cat", "Have a pet cat the size of an elephant"],
    ["Give up your phone for a month", "Give up dessert for a year"],
    ["Only drive on back roads", "Only drive on highways"],
    ["Always have to say what you're thinking", "Never be able to speak again"],
  ],

  /* ---------- Daily games: outside links (open in a new tab) ---------- */
  daily: [
    { name: "Wordle", desc: "Guess the five-letter word in six tries", url: "https://www.nytimes.com/games/wordle/index.html", color: "#6aaa64" },
    { name: "Connections", desc: "Sort 16 words into four secret groups", url: "https://www.nytimes.com/games/connections", color: "#b49fdc" },
    { name: "Strands", desc: "A themed word search with a twist", url: "https://www.nytimes.com/games/strands", color: "#c0ddd9" },
    { name: "The Mini", desc: "A crossword you can finish in a minute", url: "https://www.nytimes.com/crosswords/game/mini", color: "#6493e6" },
    { name: "TimeGuessr", desc: "Guess where and when a photo was taken", url: "https://timeguessr.com", color: "#f2c14e" },
    { name: "Worldle", desc: "Name the country from its silhouette", url: "https://worldle.teuteuf.fr", color: "#7cf0ff" },
    { name: "Travle", desc: "Cross the map one border at a time", url: "https://travle.earth", color: "#ff9f6b" },
    { name: "Framed", desc: "Guess the movie one frame at a time", url: "https://framed.wtf", color: "#ff5fa2" },
    { name: "Globle", desc: "Find the mystery country with hot/cold hints", url: "https://globle-game.com", color: "#8be08b" },
    { name: "Bandle", desc: "Name the song as instruments join in", url: "https://bandle.app", color: "#c69bff" },
  ],
};
